--------------------------------------------------------------
 --  Copyright (c) 2011-2021 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	/home/zlw/fpga/anlogic/eg4s2/bldc/al_ip/cpu_regs/cpu_regs.vhd
 -- Date	:	2020 04 29
 -- TD version	:	4.6.18154
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY regfile_dp IS
PORT (
	do	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0);

	di	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);
	waddr: IN STD_LOGIC_VECTOR(4 DOWNTO 0);
	raddr	: IN STD_LOGIC_VECTOR(4 DOWNTO 0);
	we	: IN STD_LOGIC;
	wclk	: IN STD_LOGIC
	);
END regfile_dp;

ARCHITECTURE struct OF regfile_dp IS

	BEGIN
	inst : EG_LOGIC_DRAM
		GENERIC MAP (
			DATA_WIDTH_W	=> 32,
			ADDR_WIDTH_W	=> 5,
			DATA_DEPTH_W	=> 32,
			DATA_WIDTH_R	=> 32,
			ADDR_WIDTH_R	=> 5,
			DATA_DEPTH_R	=> 32,
			INIT_FILE	=> "zero.mif"
		)
		PORT MAP (
			di		=> di,
			waddr	=> waddr,
			we		=> we,
			wclk		=> wclk,
			do		=> do,
			raddr	=> raddr
		);

END struct;
